### ISSUE TITLE
What code in the sidebar.php for popular posts

### ISSUE THREAD

**Issue by ghost** [tovic/popular-post-plugin-for-mecha-cms#1]
Hello developer,

I am currently working on my new Mecha CMS project at https://bloggertempel.de/mechacmsblog . I would like to show popular posts in the left sidebar and can nowhere find which code in the sidebar.php must be integrated.

Your official website is still not available :)

Can you show me here?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
Your donation has been received. And it is on hold, thanks. Just a little more, and the website will be active again for about 5 months.

About the popular post code:

``` .html
<aside class="col-md-3 blog-sidebar">
  <!-- begin popular posts -->
  <?php Shield::chunk('block.widget', array(
      'title' => $speak->widget->popular_posts,
      'content' => Widget::popularPost()
  )); ?>
  <!-- end popular posts -->
  …
</aside>
```

&hellip;

**Comment by ghost** [comment]
I am very pleased that the small donation was well received. My pleasure! It would be very helpful if your website goes online again. Since I have linked several times to link my readers to the Mecha CMS.

Thanks for this PHP code, which I could successfully integrate in the sidebar.php. The result you see in the blog with me - >> (above the link was once again)

I have now some of your repositories to the Mecha plugins to have it in my GitHub account to have. There I added everywhere a German description and so know the German Mecha CMS users.

**Comment by taufik-nurrohman** [comment]
The site is now online :smiley_cat:
